# Generated by Django 2.1 on 2018-09-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguradodados',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seguradodados',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='segurado',
            name='emails',
            field=models.ManyToManyField(blank=True, null=True, to='cotacao.Email'),
        ),
        migrations.AlterField(
            model_name='segurado',
            name='telefones',
            field=models.ManyToManyField(blank=True, null=True, to='cotacao.Telefone'),
        ),
    ]
